// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DiscussionController from "./discussion_controller.js"
application.register("discussion", DiscussionController)

import ExportPageController from "./export_page_controller.js"
application.register("export-page", ExportPageController)

import NotificationController from "./notification_controller.js"
application.register("notification", NotificationController)

import VesselFiltersController from "./vessel_filters_controller.js"
application.register("vessel-filters", VesselFiltersController)
