send_data_import_reminders:
  cron: "0 0 1,3 * *"
  class: "ServiceWorker"
  args:
    - 'send_data_import_reminders'

send_data_import_reminders_test1:
  cron: "0 0 16 * *"
  class: "ServiceWorker"
  args:
    - 'send_data_import_reminders'
